config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  d_configs:
    src: config/nvim/lua/configs
    dst: ~/.config/nvim/lua/configs
  d_core:
    src: config/nvim/lua/core
    dst: ~/.config/nvim/lua/core
  d_default_theme:
    src: config/nvim/lua/default_theme
    dst: ~/.config/nvim/lua/default_theme
  d_user:
    src: config/nvim/lua/user
    dst: ~/.config/nvim/lua/user
  d_user_example:
    src: config/nvim/lua/user_example
    dst: ~/.config/nvim/lua/user_example
  f_user_init.lua:
    src: config/nvim/lua/user/init.lua
    dst: ~/.config/nvim/lua/user/init.lua
  f_keymaps.lua:
    src: config/nvim/lua/user/keymaps.lua
    dst: ~/.config/nvim/lua/user/keymaps.lua
  f_vimspector.lua:
    src: config/nvim/lua/user/vimspector.lua
    dst: ~/.config/nvim/lua/user/vimspector.lua
profiles:
  nate-pc:
    dotfiles:
    - f_tmux.conf
    - d_alacritty
    - d_nvim
    - f_init.lua
    - d_configs
    - d_core
    - d_default_theme
    - d_user
    - d_user_example
    - f_user_init.lua
    - f_keymaps.lua
    - f_vimspector.lua
